version: "2"
services:
  web:
    image: "indragunawan/nginx-php-ext:latest"
    container_name: course-web
    ports:
        - "80:80"
    privileged: true
    volumes:
      - "./:/home/projects/course"
      - "~/.composer:/root/.composer"
    environment:
      - DOMAIN_1=course.dev|/home/projects/course/public|rewrite_index
    links:
      - "redis:redis-host"
      - "postgresql:database-host"

  postgresql:
    image: "postgres:9.4"
    container_name: course-postgresql
    ports:
      - "5433:5432"
    volumes:
      - "./var/docker/volumes/postgresql:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course

  redis:
    image: "redis:alpine"
    container_name: "course-redis"
    ports:
      - "6379:6379"